jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v2

      - name: Checkout zipper
        uses: actions/checkout@v2
        with:
          repository: lemniskett/AnyKernel3
          path: zipper

      - name: Android kernel build
        uses: lemniskett/android-kernel-actions@master
        id: build
        env:
          NAME: Art3mis
        with:
          arch: arm64
          compiler: gcc/10
          defconfig: RMX2185_defconfig
          image: Image.gz-dtb

      - name: Debug - List workspace contents
        run: ls -R /github/workspace

      - name: Debug - Check build output
        run: echo "Build output file: ${{ steps.build.outputs.outfile }}"

      - name: Debug - List contents of /github/workspace/zipper
        run: ls -l /github/workspace/zipper

      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ steps.build.outputs.outfile }}
          token: ${{ secrets.GITHUB_TOKEN }}
